### ISSUE TITLE
Not working in swift 4 & Xcode 11

### ISSUE THREAD

**Issue by rpspurushoth** [yarodevuci/VKMusic#11]
We cant able to working in swift 4. its show lot of compilation errors

**Comment by yarodevuci** [comment]
@rpspurushoth  I am sorry to hear that, I have not touched this project for a while, neither updated it to SWIFT 4, When I get time I will do so, but for now you have to fix the errors yourself ...

**Comment by yarodevuci** [comment]
@rpspurushoth updated to SWIFT 4
