### ISSUE TITLE
can not get access to the music.

### ISSUE THREAD

**Issue by Miramas** [yarodevuci/VKMusic#7]
I get the windows phone authentification in a web. It asks for page info and audio, but when i click allow. It fails. WebView gives an error: 
{"error" : "invalid_access",
"error_description" : "security issue"}

console: _WebFilterIsActive returning: NO

**Comment by yarodevuci** [comment]
I heard about this issue. Working to fix that. VK might block the secret path again that allowed to trick Music API

**Comment by yarodevuci** [comment]
@Miramas Вообщем пока музыку сново прикрыли ....

**Comment by Miramas** [comment]
@yarodevuci очень жаль( кстати тогда интересно каким образом работает JDPlayer?

**Comment by axenovV** [comment]
@Miramas Насчет JDPlayer хз, но подобные приложения в сторе прикидываются официальным приложением от вк, и id и bundle берут от оф прилы.

**Comment by yarodevuci** [comment]
@Miramas @axenovV Ну вот я как раз использовал один из таких найди и его накрыли. Вот ищу другие

**Comment by axenovV** [comment]
@yarodevuci  https://appsto.re/ru/8G9phb.i это смотрел? Тоже прикидывается оф прилой.

**Comment by axenovV** [comment]
@yarodevuci  прочекал, его id работает, только скоро его тоже наверное забанят.

**Comment by yarodevuci** [comment]
@axenovV напиши его айди мне в ВК и попробуй работает ли оно в моем приложение
