### ISSUE TITLE
Problems with authentication

### ISSUE THREAD

**Issue by DZamataev** [yarodevuci/VKMusic#8]
Illustration video with logs: https://www.dropbox.com/s/a7oxvnxq8iruh15/VKMusic_auth_error_issue_github.mov?dl=0
Authentication does not work on device also.

**Comment by yarodevuci** [comment]
@DZamataev Привет. Я знаю.. тебе нужно найти новый эпп айди с которым вк музыка бы работала. В данный момент проэкт на закрытом этапе. Но есть возможность что попадет в эпп стор. Потом могу дать ссылку
